// build-cdn.mjs — assemble a static, backend-free build of the games compendium for a public CDN
// (Cloudflare Pages, etc). The output in ./dist is pure client: every game plays locally — pass-and-play,
// solo, or vs the AI — and NOTHING reaches for a server. Run:  node tools/build-cdn.mjs
//
// What it does, and why:
//   • copies only the client the browser needs (index.html + web/ + src/); no server/, tools/, tests,
//     node_modules, .git or .claude ever go near the artifact — so no infrastructure leaks;
//   • drops the online-only Community page (web/lobby.*) since there's no relay to talk to;
//   • writes a NON-neutral web/config.local.js that sets { online:false } — the one switch that makes
//     config.js strip every online affordance (relay light, login, "Play online" mode);
//   • writes a Cloudflare _headers file with sensible security headers (CSP, nosniff, frame-ancestors …).
// The result is safe to publish: view-source reveals no host, no realm, no tailnet name — just games.

import { rm, mkdir, cp, writeFile, readFile, readdir, stat } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DIST = join(ROOT, 'dist');

// Files the browser actually loads. Anything not here does not ship.
const INCLUDE = ['index.html', 'web', 'src'];
// Online-only pages/modules with no purpose in a backend-free build.
const DROP = ['web/lobby.html', 'web/lobby.js'];

const OFFLINE_CONFIG = `// config.local.js — CDN build (generated by tools/build-cdn.mjs). Backend-free and safe to publish:
// no host, realm or tailnet name appears anywhere. { online:false } tells config.js to strip every
// online affordance so the pages never open a socket. Every game still plays locally / solo / vs AI.
window.__GAMES_CONFIG__ = { online: false };
`;

// A same-origin static app: allow inline <style>/<script>/importmap and inline handlers (the pages use
// them), local workers (board AI) and data: assets; forbid everything cross-origin. connect-src 'self'
// keeps the only fetches (Sidoku's puzzle files) working while blocking any call off-origin.
const HEADERS = `/*
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: no-referrer
  Permissions-Policy: geolocation=(), microphone=(), camera=(), interest-cohort=()
  Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; media-src 'self' data:; connect-src 'self'; worker-src 'self' blob:; child-src 'self' blob:; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; object-src 'none'
`;

async function exists(p) { try { await stat(p); return true; } catch { return false; } }

await rm(DIST, { recursive: true, force: true });
await mkdir(DIST, { recursive: true });

for (const item of INCLUDE) {
  await cp(join(ROOT, item), join(DIST, item), { recursive: true });
}
for (const rel of DROP) {
  await rm(join(DIST, rel), { force: true });
}
await writeFile(join(DIST, 'web', 'config.local.js'), OFFLINE_CONFIG);
await writeFile(join(DIST, '_headers'), HEADERS);

// Cloudflare Pages caps files at 25 MiB, and the Sidoku puzzle banks are huge (one puzzle per line —
// hundreds of thousands of them). Trim each to a generous line-boundary sample so the CDN build fits
// and stays lean; the full banks remain on the origin server. 4 MiB is still tens of thousands of puzzles.
const PUZZLE_CAP = 4 * 1024 * 1024;
const resDir = join(DIST, 'web', 'games', 'sidoku', 'resources');
for (const f of await readdir(resDir)) {
  if (!f.endsWith('.txt')) continue;
  const p = join(resDir, f);
  const buf = await readFile(p);
  if (buf.length <= PUZZLE_CAP) continue;
  let cut = buf.lastIndexOf(0x0a, PUZZLE_CAP); // keep whole lines only (don't split a puzzle)
  if (cut < 0) cut = PUZZLE_CAP;
  await writeFile(p, buf.subarray(0, cut + 1));
  console.log(`trimmed ${f}: ${(buf.length / 1048576).toFixed(1)} MiB -> ${((cut + 1) / 1048576).toFixed(1)} MiB`);
}

// Count what we shipped, and hard-fail if anything internal slipped in.
async function walk(dir) {
  let n = 0; const bad = [];
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) { const r = await walk(p); n += r.n; bad.push(...r.bad); }
    else { n++; if (/\.claude|relay\.js|rooms\.js|settings\.json/.test(p)) bad.push(p); }
  }
  return { n, bad };
}
const { n, bad } = await walk(DIST);
if (bad.length) { console.error('REFUSING: internal files in dist:', bad); process.exit(1); }
console.log(`dist/ ready — ${n} files. Deploy: drag ./dist into Cloudflare Pages (or 'wrangler pages deploy dist').`);
console.log(`Dropped online-only: ${DROP.join(', ')}.  config.local.js => { online:false }.  _headers written.`);
